name: Fetch m3u8 URL

on:
  schedule:
    - cron: "*/30 * * * *"  # Run every 30 minutes
  workflow_dispatch:

jobs:
  fetch-m3u8:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies (mitmproxy, selenium)
      run: |
        pip install mitmproxy selenium

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 'latest'

    # Run mitmproxy and selenium
    - name: Run mitmproxy and selenium to fetch m3u8 URL
      run: |
        mitmdump -s fetch_m3u8.py --set block_global=false --set stream_large_bodies=5m &
        sleep 5  # Give mitmproxy some time to initialize
        python run_selenium.py  # Run selenium to visit the website
        sleep 20  # Keep mitmproxy running for 20 seconds after Selenium finishes
