name: Fetch m3u8 URL

on:
  workflow_dispatch:
    inputs:
      webpage_url:
        description: 'Enter the webpage URL'
        required: true
        type: string

jobs:
  extract_m3u8:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install requests beautifulsoup4

    - name: Extract m3u8 URL
      run: |
        python fetch_m3u8.py "${{ github.event.inputs.webpage_url }}"
