name: Play YouTube Video

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'YouTube Video URL'
        required: true
        default: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ'

jobs:
  play_video:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install VLC
        run: sudo apt-get install -y vlc

      - name: Play YouTube Video
        run: |
          chmod +x play_youtube.sh  # if using the shell script
          ./play_youtube.sh ${{ github.event.inputs.video_url }}
          # or for the Python script
          python3 play_youtube.py ${{ github.event.inputs.video_url }}
