name: Scrape Live Stream URL

on:
  workflow_dispatch:  # Allow manual trigger with URL input
    inputs:
      url:
        description: "The URL to scrape for m3u8 links"
        required: true
        default: "https://news.abplive.com/live-tv"

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Use Node.js version compatible with Puppeteer

    - name: Install Puppeteer
      run: npm install puppeteer

    - name: Run Puppeteer script with dynamic URL
      env:
        TARGET_URL: ${{ github.event.inputs.url }}  # Pass URL as environment variable
      run: |
        node puppeteer-script.js | tee puppeteer_output.txt

    - name: Display captured .m3u8 URL
      run: |
        cat puppeteer_output.txt
        grep 'Found .m3u8 URL:' puppeteer_output.txt || echo "No .m3u8 URL found."

